### ISSUE TITLE
Distrobox repository vanished

### ISSUE THREAD

**Issue by amotl** [krillefear/distrobox#1]
Dear @krillefear,

I just found that the Distrobox project [1] by Luca Di Maio (@89luca89) I was looking at just yesterday, seems to have vanished. Luckily, ~~@ABDELILAH-OUHAJJOU had a copy [2]~~ @misobarisic had a recent copy [2], so I forked it to [3].

Does anyone know what might be going on?

With kind regards,
Andreas.

[1] https://github.com/89luca89/distrobox
[2] https://github.com/misobarisic/distrobox
[3] https://github.com/cicerops/distrobox

**Comment by amotl** [comment]
Thanks for cross-posting to https://github.com/castrojo/ublue/issues/38, @Okharev.

**Comment by rmnscnce** [comment]
@89luca89's GitHub account and all of its repositories are being flagged by GitHub for some unknown-yet reasons.

He has made a mirror on GitLab [here](https://gitlab.com/89luca89/distrobox/) for the time being.

Reference: https://t.me/distrobox/604

**Comment by amotl** [comment]
Dear @rmnscnce,

thank you very much for sharing this. Best wishes to Luca for getting his account restored [^1].

With kind regards,
Andreas.

[^1]: https://twitter.com/LucaDiMaio11/status/1526458070976577538

**Comment by misobarisic** [comment]
There's also my [fork](https://github.com/misobarisic/distrobox). I'll try keeping it up to date with the gitlab upstream.

**Comment by amotl** [comment]
Dear @github,

can we humbly ask you to look into this matter?

With kind regards,
Andreas.

**Comment by rmnscnce** [comment]
It has been reinstated by GitHub
![image](https://user-images.githubusercontent.com/31619874/168826298-e76106ea-1f81-476b-bfd7-a84eadfee7d2.png)

**Comment by 89luca89** [comment]
All is back to normal :-)

**Comment by amotl** [comment]
Hi again,

great. Can you share any details why GitHub might have originally flagged your account? Otherwise, let's just close this issue again.

Keep up the spirit and with kind regards,
Andreas.

**Comment by 89luca89** [comment]
> Hi again,
> 
> great. Can you share any details why GitHub might have originally flagged your account? Otherwise, let's just close this issue again.
> 
> Keep up the spirit and with kind regards, Andreas.

I'll update when I know something more, for now I just know that they unflagged me, but the support ticket is still open and not updated

**Comment by 89luca89** [comment]
Seems like it had to do with github actions 

![Screenshot_20220517-161757](https://user-images.githubusercontent.com/598882/168833186-52344e0a-61e8-4a97-982f-1eee5f29ae35.png)

Will need to migrate them elsewhere

**Comment by amotl** [comment]
Dear Luca,

all right, thank you for the update. Good luck that this will not happen again to save you the trouble.

Cheers,
Andreas.

P.S.: Thanks for having us, @krillefear.
